=== shamansir/shamansir.github.com/_history/2009-winter/occurences.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<xs:schema xmlns="http://ulric-wilfred.name" elementFormDefault="qualified" targetNamespace="http://ulric-wilfred.name" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="occurences" type="OccurenceListType" />
  <xs:complexType name="OccurenceInfoType">
    <xs:sequence>
      <xs:element name="id" type="xs:string" />
      <xs:element minOccurs="0" name="name" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="type" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="OccurenceListType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="occurence" type="OccurenceInfoType" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="group" type="OccurenceGroupType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="OccurenceGroupType">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element maxOccurs="unbounded" name="occurence" type="OccurenceInfoType" />
    </xs:sequence>
    <xs:attribute name="shortname" type="xs:string" use="optional" />
  </xs:complexType>
</xs:schema>

=== shamansir/shamansir.github.com/_history/2009-autumn/occurences.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./occurences.xsl"?>
<occurences 
    xmlns="http://ulric-wilfred.name" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://ulric-wilfred.name ./occurences.xsd">
    <occurence type="openid">
        <id>ulric.wilfred</id>
    </occurence>
    <group shortname="messengers">
        <name>Messengers</name>
	    <occurence type="icq">
	        <id>5255496</id>
	        <name>shaman.sir</name>
	    </occurence>
	    <occurence type="skype">
	        <id>shaman.sir</id>
	    </occurence>
	    <occurence type="jabber">
	        <id>ulric.wilfred@jabber.org</id>
	        <name>ulric.wilfred</name>
	    </occurence>
	    <occurence type="gtalk">
	        <id>shaman.sir</id>
	    </occurence>        
    </group>
    <group shortname="email">
        <name>E-mail</name>    
	    <occurence type="gmail">
	        <id>shaman.sir</id>
	    </occurence>
	    <!--
	    <occurence type="yahoo-profile">
	        <id>ulric.wilfred</id>
	    </occurence>
	    -->
	    <occurence type="yahoo">
	        <id>ulric.wilfred</id>
	    </occurence>
        <!--
        <occurence type="zenbe">
            <id>ulric.wilfred</id>
        </occurence>
        -->	    	    
    </group>
    <group shortname="blogging">
        <name>Blogging</name>
	    <occurence type="wikidot">
	        <id>shaman-sir</id>
	        <name>Шаманские бредни: вики-проекция</name>
	    </occurence>
	    <occurence type="wordpress">
	        <id>shamansir</id>
	        <name>Шаманские бредни</name>
	    </occurence>
	    <!-- <occurence type="livejournal">
	        <id>tungusso</id>
	    </occurence> -->	    
    </group>
    <group shortname="developing">
        <name>Developers' communities</name>
        <occurence type="launchpad">
            <id>shaman-sir</id>
            <name>shaman.sir</name>
        </occurence>        
        <occurence type="googlecode">
            <id>shaman.sir</id>
        </occurence>
        <occurence type="stack-overflow">
            <id>53887</id>
            <name>shaman.sir</name>
        </occurence>             
    </group>
    <group shortname="podcasting">
        <name>Podcasting</name>
        <occurence type="rpod">
            <id>20148</id>
            <name>Ulric Wilfred</name>
        </occurence>        
    </group>
    <group shortname="music">
        <name>Music Related</name>
        <occurence type="lastfm">
            <id>shamansir</id>
        </occurence>           
    </group>
    <group shortname="art">
        <name>Art</name>
        <occurence type="deviantart">
            <id>shaman-sir</id>
        </occurence>             
    </group>
    <group shortname="wiki">
        <name>Wiki</name>
        <occurence type="wikidot-profile">
            <id>ulric-wilfred</id>
            <name>Ulric Wilfred</name>
        </occurence>
        <occurence type="wikibooks">
            <id>Shaman.sir</id>
        </occurence>                
    </group>    
    <group shortname="languages">
        <name>Learning Languages and Traslations</name>
        <occurence type="livemocha">
            <id>1788246</id>
            <name>shaman.sir</name>
        </occurence>        
        <occurence type="notabenoid">
            <id>73</id>
            <name>zokotuhaFly</name>
        </occurence>             
    </group>
    <group shortname="social">
        <name>Social</name>
        <occurence type="linked-in">
            <id>shamansir</id>
            <name>Anton K.</name>
        </occurence>        
        <occurence type="facebook">
            <id>1110764858</id>
            <name>Ulric Wilfred</name>
        </occurence>   
        <occurence type="vkontakte">
            <id>54426</id>
            <name>Anton Shamansir</name>
        </occurence>
        <!--
        <occurence type="bestpersons">
            <id>shamansir</id>
        </occurence>         
         --> 
    </group>
    <group shortname="microblogging">
        <name>Microblogging</name>
        <occurence type="twitter">
            <id>shaman_sir</id>
        </occurence>        
        <occurence type="plurk">
            <id>shamansir</id>
        </occurence>
    </group>
    <group shortname="coblogging">
        <name>Collective Blogging</name>
        <occurence type="dirty">
            <id>8666</id>
            <name>tunguss</name>
        </occurence>
        <occurence type="leprosorium">
            <id>15140</id>
            <name>zokotuhaFly</name>
        </occurence>
        <occurence type="habrahabr">
            <id>zokotuhafly</id>
            <name>zokotuhaFly</name>
        </occurence>
        <occurence type="scarypeople">
            <id>1194</id>
            <name>zokotuhaFly-SS</name>
        </occurence>    
        <!--
        <occurence type="autokadabra">
            <id>tunguss</id>
        </occurence>
        -->         
    </group>                  
    <group shortname="video-sharing">
        <name>Video Sharing</name>
        <occurence type="vimeo">
            <id>1229207</id>
            <name>Ulric Wilfred</name>
        </occurence>             
    </group>
    <group shortname="special">
        <name>Other Specialized Sites</name>
	    <occurence type="ag">
	        <id>shamanStillSir</id>
	    </occurence>    	    
	    <!-- 
	    <occurence type="todoist">
	        <id>shamansr</id>
	    </occurence>
	    -->
	    <!-- TODO: add
		    <occurence type="bfeed">
	            <id>shaman_sir</id>
	        </occurence>
	        http://bfeed.ru/users/shaman_sir
	        <occurence type="livefeed">
	            <id>shaman_sir</id>
	            http://www.livelib.ru/reader/shaman_sir/profile
	        </occurence>
	        <occurence type="chimp">
	            <id>shamansir</id>
	            http://shamansir.mp/
	        </occurence>
	        <occurence type="torrents">
                <id>2689745</id>
                <name>shaman.s.Sir</name>
            </occurence>
	        <occurence type="scribbler">
	            <id>805</id>
	            <name>shaman.sir</name>
	            http://www.scribbler.ru/user/profile/805
	        </occurence>        
        -->
        <!-- TODO: register/add?
	        python
	        minna no nihongo
	        tripster
	        flagatrip
	        projecteuler.net
	        indiegames
	        sketchup
	        netvibes
	        zenbe
	        evernote
	        plurk
	        activestate
	        microformats
         -->	    
	    
    </group>
    <group shortname="online-games">
        <name>Online Games</name>
        <occurence type="second-life">
            <id>Ulric Elcano</id>
        </occurence>
        <occurence type="project-torque">
            <id>2768917</id>
            <name>shaman.sir</name>
        </occurence>
        <occurence type="teeworlds">
            <id>shaman.sir</id>
        </occurence>
    </group>
    <!--
    <occurence type="foxmarks">
        <id>Zokotuha-Fly</id>
    </occurence>
    <occurence type="remember-the-milk">
        <id>ulric.wilfred</id>
    </occurence>        
    <occurence type="sdf">
        <id>shamansr</id>
    </occurence>
    <occurence type="vimeo">
    </occurence>
    <occurence type="rsdn">
    </occurence>
    <occurence type="vox">
    </occurence>    
    <occurence type="blogger">
    </occurence>
    <occurence type="moikrug">
    </occurence>      
    -->
</occurences>
