=== shamansir/shamansir.github.com/_history/2007-autumn/data/temp/xsd/localization.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp2 (http://www.altova.com) by Anthony Kotenko (EmDev LLC) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:g="http://www.shaman-sir.by.ru/XSD/Generic"
           targetNamespace="http://www.shaman-sir.by.ru/XSD/Localization"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:import namespace="http://www.shaman-sir.by.ru/XSD/Generic" schemaLocation="./generic.xsd"/>
	<xs:element name="localization">
		<xs:annotation>
			<xs:documentation>localization languages</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="language" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
              <xs:element name="string" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="g:pageLanguageType" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
      <xs:attribute name="select" type="g:pageLanguageType" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="localization-source">
    <xs:annotation>
      <xs:documentation>
        Specifies localization source, which must consist of localization element
        and also to be conformant with the Localization scheme
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="src" type="xs:anyURI" use="required"/>
      <xs:attribute name="select" type="g:pageLanguageType" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== shamansir/shamansir.github.com/_history/2007-autumn/data/localization.xml
<?xml version="1.0" encoding="utf-8"?>
<l:localization xmlns:g="http://www.shaman-sir.by.ru/XSD/Generic"
        xmlns:l="http://www.shaman-sir.by.ru/XSD/Localization"        
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://www.shaman-sir.by.ru/XSD/Localization ./xsd/localization.xsd">
  <l:language id="en">
    <l:string id="l:definition-label">Site definition, which is usually background image</l:string>
    <l:string id="l:site-introduction">welcome to shaman.sir homesite :: please feel yourself safe</l:string>
    <l:string id="l:skip-nav-caption">Skip navigation blocks and proceed to content</l:string>
    <l:string id="l:skip-nav-link">Skip to content</l:string>
    <l:string id="l:proceed-sub-nav-caption">Proceed to sub-navigation, if required</l:string>
    <l:string id="l:proceed-sub-nav-link">Proceed to sub-navigation</l:string>
    <l:string id="l:current-page-caption">Current page</l:string>
    <l:string id="l:current-page-link-prefix">You are @</l:string>
    <l:string id="l:proceed-to-top-caption">Proceed to the top</l:string>
    <l:string id="l:proceed-to-top-link">Proceed to the top</l:string>
  </l:language>
  <l:language id="ru">
    <l:string id="l:definition-label">Описание сайта, по умолчанию представляющее собой фоновое изображение</l:string>
    <l:string id="l:site-introduction">добро пожаловать на домашнюю страницу shaman.sir :: пожалуйста чувствуйте себя комфортно</l:string>
    <l:string id="l:skip-nav-caption">Пропустить навигацию и перейти к содержимому</l:string>
    <l:string id="l:skip-nav-link">Перейти к содержимому</l:string>
    <l:string id="l:proceed-sub-nav-caption">Если необходимо, перейти к навигации по разделам</l:string>
    <l:string id="l:proceed-sub-nav-link">Перейти к навигации по разделам</l:string>
    <l:string id="l:current-page-caption">Текущая страница</l:string>
    <l:string id="l:current-page-link-prefix">Вы находитесь на странице</l:string>
    <l:string id="l:proceed-to-top-caption">Перейти к началу</l:string>
    <l:string id="l:proceed-to-top-link">Перейти к началу</l:string>
  </l:language>  
</l:localization>

=== shamansir/shamansir.github.com/_history/2007-autumn/data/temp/localization.xml
<?xml version="1.0" encoding="utf-8"?>
<l:localization xmlns:g="http://www.shaman-sir.by.ru/XSD/Generic"
        xmlns:l="http://www.shaman-sir.by.ru/XSD/Localization"        
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://www.shaman-sir.by.ru/XSD/Localization ./xsd/localization.xsd">
  <l:language id="en">
    <l:string id="l:definition-label">Site definition, which is usually background image</l:string>
    <l:string id="l:site-introduction">welcome to shaman.sir homesite :: please feel yourself safe</l:string>
    <l:string id="l:a">enn</l:string>
  </l:language>
  <l:language id="ru">
    <l:string id="l:definition-label">Описание сайта, по умолчанию представляющее собой фоновое изображение</l:string>
    <l:string id="l:site-introduction">добро пожаловать на домашнюю страницу shaman.sir :: пожалуйста чувствуйте себя комфортно</l:string>
    <l:string id="l:a">rru</l:string>
  </l:language>  
</l:localization>
