=== shamansir/shamansir.github.com/_history/2009-autumn/contacts.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<xs:schema xmlns="http://ulric-wilfred.name" elementFormDefault="qualified" 
           targetNamespace="http://ulric-wilfred.name" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="contacts" type="ContactListType" />
  <xs:complexType name="ContactInfoType">
    <xs:sequence>
      <xs:element name="id" type="xs:string" />
      <xs:element minOccurs="0" name="name" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="type" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="ContactListType">
    <xs:sequence>
    	<xs:element minOccurs="0" maxOccurs="unbounded" name="contact"
    		type="ContactInfoType" />
    	<xs:element minOccurs="0" maxOccurs="unbounded" name="group"
    		type="ContactsGroupType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ContactsGroupType">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element maxOccurs="unbounded" name="contact" type="ContactInfoType" />
    </xs:sequence>
    <xs:attribute name="shortname" type="xs:string" use="optional" />
  </xs:complexType>
</xs:schema>

=== shamansir/shamansir.github.com/_history/2009-autumn/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./contacts.xsl"?>
<contacts 
    xmlns="http://ulric-wilfred.name" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://ulric-wilfred.name ./contacts.xsd">
    <group shortname="messengers">
        <name>Messengers</name>
        <contact type="skype">
            <id>shaman.sir</id>
        </contact>
        <contact type="jabber">
            <id>ulric.wilfred@jabber.org</id>
            <name>ulric.wilfred</name>
        </contact>
        <contact type="gtalk">
            <id>shaman.sir</id>
        </contact>
        <contact type="yahoo">
            <id>ulric.wilfred</id>
        </contact>
        <contact type="icq">
            <id>5255496</id>
            <name>shaman.sir</name>
        </contact>        
    </group>
    <group shortname="email">
        <name>E-Mail</name>
        <contact type="gmail">
            <id>shaman.sir</id>
        </contact>
        <contact type="yahoo-mail">
            <id>ulric.wilfred</id>
        </contact>         
    </group>        
</contacts>
